server:
  port: 8081
  tomcat:
    connection-timeout: 300000
    keep-alive-timeout: 300000

spring:
  application:
    name: lead-enrichment-api
  mvc:
    async:
      request-timeout: 300000
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:pgsqldev}
  jpa:
    show-sql: false
    format-sql: false
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      write-dates-as-timestamps: false

serper:
  api:
    url: ${SERPER_API_URL:http://localhost:7000}

api:
  key: ${API_KEY:b6vxAgj5KG5HPGCKlQQ7}
  encryption:
    secret: ${ENCRYPTION_SECRET:f44sGktPn25aHIuTfi9KbIwNnh8qO0xdbn+KmwwePz8=}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true

logging:
  level:
    root: INFO
    solutions.pdroti: INFO
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"